### ISSUE TITLE
后端搭建相关问题与坑

### ISSUE THREAD

**Issue by lingcheng-1** [pwp-app/pixiviz-server#2]
继https://github.com/pwp-app/pixiviz/issues/17之后的后端遇到的问题。
上传至centos服务器后，吸取前端的踩坑经验把npm更新，然后使用nrm修改为npm官方源。
使用npm insatll进行依赖安装后开始出现报错。
根据提示修改安装依赖命令为npm install --legacy-peer-deps后即可解决
![图片](https://user-images.githubusercontent.com/71746286/121679408-e189e200-caea-11eb-93ed-ddb3342d089e.png)
然后查看package.json中的启动命令。
[root@VM-12-6-centos pixiv]# npm start

> pixiviz-backend@1.7.1 start
> egg-scripts start --daemon --title=egg-server-pixivc-backend

[egg-scripts] Starting egg application at /pixiv
[egg-scripts] Run node --no-deprecation /pixiv/node_modules/egg-scripts/lib/start-cluster {"title":"egg-server-pixivc-backend","baseDir":"/pixiv","framework":"/pixiv/node_modules/egg"} --title=egg-server-pixivc-backend
[egg-scripts] Save log file to /root/logs
[egg-scripts] Wait Start: 1...
[egg-scripts] Wait Start: 2...
[egg-scripts] tail -n 100 /root/logs/master-stderr.log
[egg-scripts] Got error when startup: 
[egg-scripts] 2021-06-11 19:28:06,279 ERROR 23925 nodejs.MODULE_NOT_FOUNDError: [egg-core] load file: /pixiv/config/config.default.js, error: Cannot find module './keys'
[egg-scripts] Require stack:
[egg-scripts] - /pixiv/config/config.default.js
[egg-scripts] - /pixiv/node_modules/egg-core/lib/utils/index.js
[egg-scripts] - /pixiv/node_modules/egg-core/lib/egg.js
[egg-scripts] - /pixiv/node_modules/egg-core/index.js
[egg-scripts] - /pixiv/node_modules/egg/lib/application.js
[egg-scripts] - /pixiv/node_modules/egg/index.js
[egg-scripts] - /pixiv/node_modules/egg-cluster/lib/agent_worker.js
[egg-scripts] Require stack:
[egg-scripts] - /pixiv/config/config.default.js
[egg-scripts] - /pixiv/node_modules/egg-core/lib/utils/index.js
[egg-scripts] - /pixiv/node_modules/egg-core/lib/egg.js
[egg-scripts] - /pixiv/node_modules/egg-core/index.js
[egg-scripts] - /pixiv/node_modules/egg/lib/application.js
[egg-scripts] - /pixiv/node_modules/egg/index.js
[egg-scripts] - /pixiv/node_modules/egg-cluster/lib/agent_worker.js
[egg-scripts]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
[egg-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
[egg-scripts]     at Module.require (internal/modules/cjs/loader.js:957:19)
[egg-scripts]     at require (internal/modules/cjs/helpers.js:88:18)
[egg-scripts]     at Object.<anonymous> (/pixiv/config/config.default.js:5:14)
[egg-scripts]     at Module._compile (internal/modules/cjs/loader.js:1068:30)
[egg-scripts]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
[egg-scripts]     at Module.load (internal/modules/cjs/loader.js:933:32)
[egg-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
[egg-scripts]     at Module.require (internal/modules/cjs/loader.js:957:19)
[egg-scripts] code: "MODULE_NOT_FOUND"
[egg-scripts] requireStack: ["/pixiv/config/config.default.js","/pixiv/node_modules/egg-core/lib/utils/index.js","/pixiv/node_modules/egg-core/lib/egg.js","/pixiv/node_modules/egg-core/index.js","/pixiv/node_modules/egg/lib/application.js","/pixiv/node_modules/egg/index.js","/pixiv/node_modules/egg-cluster/lib/agent_worker.js"]
[egg-scripts] name: "MODULE_NOT_FOUNDError"
[egg-scripts] pid: 23925
[egg-scripts] hostname: VM-12-6-centos
[egg-scripts] 
[egg-scripts] /pixiv/node_modules/egg-cluster/lib/agent_worker.js:32
[egg-scripts]   throw err;
[egg-scripts]   ^
[egg-scripts] 
[egg-scripts] Error [MODULE_NOT_FOUNDError]: [egg-core] load file: /pixiv/config/config.default.js, error: Cannot find module './keys'
[egg-scripts] Require stack:
[egg-scripts] - /pixiv/config/config.default.js
[egg-scripts] - /pixiv/node_modules/egg-core/lib/utils/index.js
[egg-scripts] - /pixiv/node_modules/egg-core/lib/egg.js
[egg-scripts] - /pixiv/node_modules/egg-core/index.js
[egg-scripts] - /pixiv/node_modules/egg/lib/application.js
[egg-scripts] - /pixiv/node_modules/egg/index.js
[egg-scripts] - /pixiv/node_modules/egg-cluster/lib/agent_worker.js
[egg-scripts]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
[egg-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
[egg-scripts]     at Module.require (internal/modules/cjs/loader.js:957:19)
[egg-scripts]     at require (internal/modules/cjs/helpers.js:88:18)
[egg-scripts]     at Object.<anonymous> (/pixiv/config/config.default.js:5:14)
[egg-scripts]     at Module._compile (internal/modules/cjs/loader.js:1068:30)
[egg-scripts]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
[egg-scripts]     at Module.load (internal/modules/cjs/loader.js:933:32)
[egg-scripts]     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
[egg-scripts]     at Module.require (internal/modules/cjs/loader.js:957:19) {
[egg-scripts]   code: 'MODULE_NOT_FOUND',
[egg-scripts]   requireStack: [
[egg-scripts]     '/pixiv/config/config.default.js',
[egg-scripts]     '/pixiv/node_modules/egg-core/lib/utils/index.js',
[egg-scripts]     '/pixiv/node_modules/egg-core/lib/egg.js',
[egg-scripts]     '/pixiv/node_modules/egg-core/index.js',
[egg-scripts]     '/pixiv/node_modules/egg/lib/application.js',
[egg-scripts]     '/pixiv/node_modules/egg/index.js',
[egg-scripts]     '/pixiv/node_modules/egg-cluster/lib/agent_worker.js'
[egg-scripts]   ]
[egg-scripts] }
[egg-scripts] 2021-06-11 19:28:06,288 ERROR 23912 nodejs.AgentWorkerDiedError: [master] agent_worker#1:23925 died (code: 1, signal: null)
[egg-scripts]     at Master.onAgentExit (/pixiv/node_modules/egg-cluster/lib/master.js:425:17)
[egg-scripts]     at Master.emit (events.js:376:20)
[egg-scripts]     at Messenger.sendToMaster (/pixiv/node_modules/egg-cluster/lib/utils/messenger.js:137:17)
[egg-scripts]     at Messenger.send (/pixiv/node_modules/egg-cluster/lib/utils/messenger.js:102:12)
[egg-scripts]     at ChildProcess.<anonymous> (/pixiv/node_modules/egg-cluster/lib/master.js:289:22)
[egg-scripts]     at Object.onceWrapper (events.js:483:26)
[egg-scripts]     at ChildProcess.emit (events.js:376:20)
[egg-scripts]     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
[egg-scripts] name: "AgentWorkerDiedError"
[egg-scripts] pid: 23912
[egg-scripts] hostname: VM-12-6-centos
[egg-scripts] 
[egg-scripts] 2021-06-11 19:28:06,289 ERROR 23912 [master] agent_worker#1:23925 start fail, exiting with code:1
[egg-scripts] 2021-06-11 19:28:06,289 ERROR 23912 [master] exit with code:1
[egg-scripts] 
[egg-scripts] Start got error, see /root/logs/master-stderr.log
[egg-scripts] Or use `--ignore-stderr` to ignore stderr at startup.
嘛，试了一些方法没有成功。干脆提交一个issues咨询一下。

**Comment by backrunner** [comment]
参考issue #1添加keys.js

**Comment by backrunner** [comment]
长时间没有更新，我先关闭这个issue，后续有其他问题可以再开。
