### ISSUE TITLE
Logfiles taking up space

### ISSUE THREAD

**Issue by Ruriko** [pwp-app/pixiviz-server#3]
There are 2 log files called "master-stderr.log" & "master-stdout.log" located in /root/logs/ and they both generate thousands of files with a filename structure like this 
```
master-stderr.log.20210801.232953
master-stderr.log.20210801.233006
master-stderr.log.20210801.233015
```
I tried using ubuntu logrotate but it seems to be ignoring the conf settings. It seems strange since lograte works in the directory /root/logs/pixiviz-backend/ but not /root/logs/ so I was wondering does your script have it's own built-in logrotate system cause it might be interfering with ubuntu's logrotate?

```
/root/*.log {
    hourly
    missingok
    rotate 10
    compress
    notifempty
    create 0640 www-data www-data
    sharedscripts
}
```

**Comment by backrunner** [comment]
Logs are all be managed by egg, you can take a look at `eggs/egg` for more details.
I knew that they have a plug-in named `egg-logrotator`, you may need it.

**Comment by backrunner** [comment]
In a further version, I'll integrate the `egg-logrotator` into my script, if you don't want to do this by yourself, you can wait for an update.

**Comment by Ruriko** [comment]
ok i'll wait for the next update

**Comment by backrunner** [comment]
Upgraded on master branch.
